"""Parser module for extracting recipe data from OpenAI API responses.

This module provides utilities to parse structured recipe information
from text responses generated by OpenAI, extracting recipe names, ingredients,
and cooking steps.
"""

from typing import List, Tuple


def get_recipe_items(response: str) -> Tuple[str | None, List[str], List[str]]:
    """Parse recipe information from an OpenAI API response string.

    Extracts the recipe name, ingredients list, and cooking steps from a
    formatted text response. The expected format includes:
    - A "Name:" line followed by the recipe name
    - An "Ingredients:" section with bullet points (lines starting with "-")
    - A "Steps:" section with numbered or lettered steps

    Args:
        response: The raw text response from OpenAI containing recipe information.

    Returns:
        A tuple containing:
            - name: The recipe name (str) or None if not found
            - parsed_ingredients: List of ingredient strings extracted from
              bullet points under the Ingredients section
            - steps: List of step strings extracted from the Steps section

    Example:
        >>> response = "Name: Chocolate Cake\\nIngredients:\\n- flour\\n- sugar\\n
                        Steps:\\n1. Mix ingredients"
        >>> name, ingredients, steps = get_recipe_items(response)
        >>> name
        'Chocolate Cake'
        >>> ingredients
        ['flour', 'sugar']
    """
    name = None
    parsed_ingredients: List[str] = []
    steps: List[str] = []

    lines = response.strip().splitlines()
    section = None

    for line in lines:
        low = line.lower()
        if low.startswith("name:"):
            name = line.split(":", 1)[1].strip()
            section = None
        elif low.startswith("ingredients:"):
            section = "ingredients"
        elif low.startswith("steps:"):
            section = "steps"
        elif section == "ingredients" and line.strip().startswith("-"):
            parsed_ingredients.append(line.strip()[1:].strip())
        elif section == "steps":
            stripped = line.strip()
            if stripped[:2].replace(".", "").replace(")", "").isdigit():
                steps.append(stripped)

    return name, parsed_ingredients, steps
